### ISSUE TITLE
Incorrect lisp constructs

### ISSUE THREAD

**Issue by marcus3santos** [kiselgra/c-mera#102]
Some lisp forms, like 'cond', are not implemented correctly. Could you please fix it?

**Comment by kiselgra** [comment]
To the best of my knowledge they are implemented correctly, without an example it is hard to tell what you are missing.

Maybe your problem is due to namespaces (cond is defined as a c-mera form that emits `if/else if/else` cascades, so when you want the lisp interpretation you need to use `cl:cond` or wrap your expression in `(lisp ...)`

The documentation is lacking in this regard, but you can check out our 2017 ELS paper, it goes into some detail about issues like the one I just mentioned.

**Comment by kiselgra** [comment]
I'm closing this as there was no furhter info on what the problem might have been. Feel free to re-open with more details :)
