### ISSUE TITLE
Support arbitrary command line flags like gcc's -D...

### ISSUE THREAD

**Issue by jandoerntlein** [kiselgra/c-mera#25]
It would be nice to define variables at compile-time via 
```
./cxxgen bla.cm -DDEBUG=1 -o bla
```
which then can be accessed in the source
```lisp
(format t "~a~%" *debug*) ;; or DEBUG, *DEBUG*, ... 
```
similiar to gcc's -D... flag

**Comment by jandoerntlein** [comment]
Seems to fail if used in combination with ```-o```

**Comment by kiselgra** [comment]
Can you provide an example?

**Comment by jandoerntlein** [comment]
```
$ cugen -D arch=3 test/arch-parameter.cm 
arch: 3

int main()
{
	return 0;
}

$ cugen -D arch=3 test/arch-parameter.cm -o test.cpp
Usage: cugen [-hgv] [OPTIONS] inputfile

A source-to-source compiler.
  -h, --help                  Print this help and exit.
  -i, --in=STR                Input file name (can also be given as non-option 
                              argument).
  -o, --out=STR               Output file name (if not specified we print to 
                              stdout).
  -D, --defparameter=STR      Define given value as parameter. -Dfoo=9 will have
                              the effect of (defparameter *foo* 9).
  -g, --debug                 Add debugging information such as line numbers in 
                              the output.
  -v, --verbose               Be verbose.
Excess command line arguments.
```

**Comment by kiselgra** [comment]
The problem here is ordering of the options. Clon (https://github.com/didierverna/clon) is not as flexible as we are used to from the standard GNU tools... All the options (starting with dashes) have to appear first, then the rest of the non-option arguments (in our case the input file) is listed.

I think this was more flexible with our earlier option handing, but I wanted to get rid of it as it was pretty messy...

I'll add this to the documentation, maybe we should also file a feature request with clon?

**Comment by jandoerntlein** [comment]
Alright thanks for the explanation :)
If you know that you have to pay attention it is not such a big problem.

**Comment by kiselgra** [comment]
I really didn't like this restriction either, so I added some code to re-order the command line so that the options appear first. If we add other types of options beside ```flag``` and ```stropt``` the ordering will have to be (trivially) adapted.
